version: '3.8'

services:
  pam-web-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: pam-marketing-site
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: unless-stopped